name: Generate Documentation for gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: builds docs and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.3
      with:
        working-directory: '.'
        doxyfile-path: './doxy.config'
 
    # store the doc files
    - name: Upload Output Directory
      uses: actions/upload-artifact@v2
      with:
        name: doc-files
        path: doc
        retention-days: 1 
        
  copy:
    name: copies docs to gh-pages
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    # prepare the doc files
    - name: Download Output Directory
      uses: actions/download-artifact@v2
      with:
        name: doc-files
        path: doc
        retention-days: 1 

    # prepare the doc files
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: Alexander Lerch
        author_email: alexander.lerch@gatech.edu
        message: 'auto-update docs'
        branch: gh-pages
        add: '["doc/html/*"]'
